const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const {randomUUID}=require('node:crypto');
const context={crypto:{randomUUID}};vm.createContext(context);vm.runInContext(fs.readFileSync('sync.js','utf8').split('let setPatchQueue=')[0]+'\nthis.Queue=SetPatchQueue;',context);
function storage(){const values=new Map();return{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)};}
const row={session_id:'s',exercise_id:'e',id:'1'};
test('failed network writes survive reload and are retried',async()=>{const disk=storage();const q=new context.Queue(disk,'alice',async()=>{throw new Error('offline');});q.put(row,{weight:20});assert.equal(await q.flush(),false);const writes=[];const restored=new context.Queue(disk,'alice',async x=>writes.push(x));assert.equal(restored.items.length,1);assert.equal(await restored.flush(),true);assert.equal(writes[0].patch.weight,20);assert.equal(restored.items.length,0);});
test('owners cannot read another account queue',()=>{const disk=storage();const alice=new context.Queue(disk,'alice',async()=>{});alice.put(row,{weight:20});const bob=new context.Queue(disk,'bob',async()=>{});assert.equal(bob.items.length,0);assert.equal(alice.items.length,1);});
test('edits arriving during an in-flight write are not lost',async()=>{const disk=storage();let release;let count=0;const sent=[];const q=new context.Queue(disk,'alice',async x=>{sent.push(x);if(count++===0)await new Promise(r=>release=r);});q.put(row,{weight:20});const pending=q.flush();q.put(row,{weight:22,reps:10});release();assert.equal(await pending,true);assert.equal(sent.length,2);assert.equal(sent[1].patch.weight,22);assert.equal(sent[1].patch.reps,10);assert.equal(q.items.length,0);});
test('storage errors do not silently accept an unsaved patch',()=>{const q=new context.Queue({getItem:()=>null,setItem(){throw new Error('quota');}},'alice',async()=>{});assert.throws(()=>q.put(row,{weight:20}),/quota/);assert.equal(q.items.length,0);});
test('changes to distinct fields are coalesced',()=>{const q=new context.Queue(storage(),'alice',async()=>{});q.put(row,{weight:20});q.put(row,{complete:true});assert.equal(q.items.length,1);assert.equal(q.items[0].patch.weight,20);assert.equal(q.items[0].patch.complete,true);});
